// National (Jatiyo) Unicode Fixed Keyboard Layout mapping table

export const NATIONAL_KEYMAP: Record<string, string> = {
  'a': 'ৃ',
  'b': 'ন',
  'c': 'এ',
  'd': 'ি',
  'e': 'ড',
  'f': 'আ',
  'g': '্',
  'h': 'ব',
  'i': 'হ',
  'j': 'ক',
  'k': 'ত',
  'l': 'দ',
  'm': 'শ',
  'n': 'স',
  'o': 'গ',
  'p': 'ড়',
  'q': 'ং',
  'r': 'প',
  's': 'ু',
  't': 'ট',
  'u': 'জ',
  'v': 'র',
  'w': 'য',
  'x': 'ও',
  'y': 'চ',
  'z': '্র',
  '[': 'ে',
  ']': 'ো',

  'A': 'র্',
  'B': 'ণ',
  'C': 'ঐ',
  'D': 'ী',
  'E': 'ঢ',
  'F': 'অ',
  'G': '।',
  'H': 'ভ',
  'I': 'ঞ',
  'J': 'খ',
  'K': 'থ',
  'L': 'ধ',
  'M': 'ষ',
  'N': 'ঙ', // Jatiyo shift-N is Nga
  'O': 'ঘ',
  'P': 'ঢ়',
  'Q': 'ঃ',
  'R': 'ফ',
  'S': 'ূ',
  'T': 'ঠ',
  'U': 'ঝ',
  'V': 'ল',
  'W': 'য়',
  'X': 'ঔ',
  'Y': 'ছ',
  'Z': '্য',
  '{': 'ৈ',
  '}': 'ৌ',
  '1': '১', '2': '২', '3': '৩', '4': '৪', '5': '৫',
  '6': '৬', '7': '৭', '8': '৮', '9': '৯', '0': '০',
};

export function translateNationalKey(key: string): string {
  return NATIONAL_KEYMAP[key] ?? key;
}
